# A sample Gemfile
source "https://rubygems.org"

gem 'em-websocket', '~> 0.5.1'

group :test do
  gem 'rspec', '~> 3.0.0'
  gem 'websocket-eventmachine-client', '~> 1.1.0'
  gem 'simplecov', '~> 0.7.1'
  gem 'capybara', '~> 2.3.0'
  gem 'poltergeist', '~> 1.5.1'
end

group :development do
  gem 'pry'
end

group :test, :development do
  gem 'sinatra'
end
